'use strict'
// auto-generated by boundation, do not update manually
/** @type {typeof import("./source/index.js") } */
module.exports = require('editions').requirePackage(__dirname, require, 'index.js')