'use strict'
// auto-generated by boundation, do not update manually
/** @type {typeof import("./source/test.js") } */
module.exports = require('editions').requirePackage(__dirname, require, 'test.js')